### ISSUE TITLE
使用 tmux 代替 screen

### ISSUE THREAD

**Issue by yggo** [crazywhalecc/cqbot-swoole#6]
如题，最开始使用的 screen 将其作为后台任务运行，但是运行大概21天进程总是自个挂掉，使用 tmux 从 5.12号挂置现在，没有掉过。

**Comment by crazywhalecc** [comment]
请问你所用的发行版是什么？

**Comment by yggo** [comment]
> 请问你所用的发行版是什么？

tmux next-2.9

**Comment by crazywhalecc** [comment]
在框架重构后用户可在新框架上自行选择daemonize方式，以后将不再给出关于screen或tmux等解决方案。
