### ISSUE TITLE
客户端重复建立两条连接

### ISSUE THREAD

**Issue by hisway** [crazywhalecc/cqbot-swoole#7]
/src/cqbot/connection/RobotWSConnection.php  line 26

`if ($v->getQQ() == $this->getQQ() && $k != $this->fd && $v->getSubType() == $this->getSubType()) {
                $this->getServer()->close($k);
                ConnectionManager::remove($k);
            }`

应该改成
`if ($v->getQQ() == $this->getQQ() && $v->fd != $this->fd && $v->getSubType() == $this->getSubType()) {
              $v->close();}`
其中$k 并不是 $v->fd，关闭时候直接$v->close()即可，否则同个客户端有可能会建立两条连接

**Comment by crazywhalecc** [comment]
这个问题似乎和客户端有关系，因为我自己的炸毛机器人项目中一直都是这样写，没遇到过两个连接的问题。
不过我每次reload时候，会在WorkerStart断掉所有websocket连接以保证数据和连接全部reload。
```php
class RobotWSConnection extends WSConnection
{
    private $qq;
    private $alias;//别名

    public function __construct(swoole_websocket_server $server, $fd, $qq, swoole_http_request $request) {
        parent::__construct($server, $fd, $request->server["remote_addr"]);
        $this->qq = $qq;
        $this->alias = ZMBuf::globals("robot_alias")[$qq] ?? "机器人" . $qq;
        foreach (ConnectionManager::getAll("robot") as $k => $v) {
            if ($v->getQQ() == $this->getQQ() && $k != $this->fd) {
                $this->getServer()->close($k);
                ConnectionManager::remove($k);
            }
        }
        CQAPI::get_version_info($this, function ($response) {
            ZMBuf::appendKey("version_info",$this->qq,$response["data"]);
        });
        $this->create_success = CQAPI::send_group_msg($this, ADMIN_GROUP, "[CrazyBot] 机器人 " . $this->getAlias() . " 已连接，链接fd：" . $this->fd);
    }
}
```

**Comment by crazywhalecc** [comment]
```php
foreach ($server->connections as $v) {
            $server->close($v);
}
```

**Comment by hisway** [comment]
这里的关键问题： $k 只是 ConnectionManager::getAll("robot")  的数组下标， $v->fd 是有意义的链接ID，这两个是不对等的，要关闭的链接ID不一定是ConnectionManager里第$k个链接

**Comment by crazywhalecc** [comment]
发现了，之前误解了你的意思。确实是个问题，这两个不是一个意义。
